server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: service-route
          uri: http://localhost:8081 # URL c?a d?ch v? con
          predicates:
            - Path=/product/**
