server:
  port: 8080

spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
        - id: auth
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
